### ISSUE TITLE
rendering of docu

### ISSUE THREAD

**Issue by DavidBruchmann** [jweiland-net/mediaconsent#2]
![image](https://user-images.githubusercontent.com/999146/163891560-626d48ed-9bb6-43c3-b5de-46f64aaa0cb0.png)

https://typo3.slack.com/archives/C028JEPJL/p1650291934370139

**Comment by ftrojahn** [comment]
@sfroemkenjw please consider rendering the recent documentation.

**Comment by sfroemkenjw** [comment]
Hello,

I have just setup the documentation rendering.

https://docs.typo3.org/p/jweiland/mediaconsent/main/en-us/

And it's now linked at TER, too.

Stefan
